### PR TITLE
Updates to civic_hackers.yml

### PR DESCRIPTION
**Pull request by jcastle-zz**
PR 3 of 3

This aligns to PR 625 in https://github.com/github/government.github.com/pulls.

### CODE REVIEW

**Comment by emanuelfeld** [comment]
I added this as a submodule, but something seems to have gotten messed up. This would just bring it up to date with the github/government.github.com repo, right? If so, I'll just fix the submodule so that it can be kept current.

**Comment by jcastle-zz** [comment]
Right, the submodule should be fixed to stay current with github/government.github.com.  I was fixing in two places because my updates are more recent than theirs.  But safer to stay in sync with what they have.

**Comment by emanuelfeld** [comment]
Ok, submodule relationship should be working now. Hopefully they'll accept your PR soon.

**Comment by emanuelfeld** [comment]
@jcastle I didn't set this up to gather timeseries type data (org/repo activity over time, growth of orgs, growth of relationships). Seemed not worth it then, because gathering the data takes _forever_ with rate-limiting and I figured issues with the data would compound over time. But maybe of interest for sets of organizations with similar governance/dev protocols? Or for certain data elements? Haven't given it too much thought.

**Comment by jcastle-zz** [comment]
I finished populating the database last night and did a manual validation on orgs and repos.  Took me a couple days to get all the data with rate limiting.  I am looking for basic information, number of CFO Act orgs represented, # of orgs, # of repos, orgs that publish the most code, # of contributions, etc.  Really somewhat of an update on your original research.  

I am using this data for code.gov metrics and dissertation DV of agency code publication.  IVs are based on conceptual model of organizations and data collection by interviews with government developers.   

Will keep you posted on findings.  Possibly looking to update your code for long-term use with code.gov for progress metrics (similar to what you were thinking with time series).  Happy to chat over coffee one day.  Send me an email (joseph.castle[at]gsa[dot]gov).

**Comment by IanLee1521** [comment]
@jcastle -- you might want to look at what @LRWeber did over in https://github.com/LLNL/llnl.github.io/blob/master/explore/scripts/MASTER.sh to pull data from GitHub. Now uses the GraphQL API and is significantly faster w.r.t. to rate limiting and number of requests used.

If you're using the REST API (v3) instead of the GraphQL API (v4) I definitely recommend giving it a look.

**Comment by jcastle-zz** [comment]
Thanks @IanLee1521!  Might look at this in the future for code.gov.  Have what I need for right now.

**Comment by emanuelfeld** [comment]
@IanLee1521 that's neat, thanks! Didn't realize that had come about since I wrote this. @jcastle would be cool to do something more akin to ecosystem modeling; that's kind of what I wanted to be doing (as suggested by the post title).

**Pull request closed without merging**
